app = "cwsgpt"
primary_region = "sin"

[env]
  SWAP = "true"

[mounts]
  source="cws"
  destination="/cws_db"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1