name: Fly Deploy
on:
  push:
    branches:
      - dev
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: pierotofy/set-swap-space@v1.0
        with:
          swap-size-gb: 4
      - uses: actions/checkout@v3
      - uses: TaiStudio/action-edit-YML@v1.0.0
        with:
          type: 'single'
          files: "./backend/data/config/config.yaml"
          elementSTR: "['data']['mongodb_url']"
          replace: "<MONGODB_URL>"
          replaceFor: ${{ secrets.MONGODB_URL }}
      - uses: TaiStudio/action-edit-YML@v1.0.0
        with:
          type: 'single'
          files: "./backend/data/config/credentials.yaml"
          elementSTR: "['openai_web_access_token']"
          replace: "<OPENAI_WEB_ACCESS_TOKEN>"
          replaceFor: ${{ secrets.OPENAI_WEB_ACCESS_TOKEN }}
      - uses: TaiStudio/action-edit-YML@v1.0.0
        with:
          type: 'single'
          files: "./backend/data/config/credentials.yaml"
          elementSTR: "['openai_api_key']"
          replace: "<OPENAI_API_KEY>"
          replaceFor: ${{ secrets.OPENAI_API_KEY }}
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
