name: Fly Deploy
on:
  push:
    branches:
      - dev
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: pierotofy/set-swap-space@v1.0
        with:
          swap-size-gb: 8
      - uses: actions/checkout@v3
      - name: set mongodb url
        uses: mingjun97/file-regex-replace@master
        with:
          regex: '<MONGODB_URL>'
          replacement: ${{ secrets.MONGODB_URL }}
          flags: "g"                  # Optional, defaults to "g"
          include: 'config.yaml'    # Optional, defaults to ".*"
          exclude: '.^'               # Optional, defaults to '.^'
          encoding: 'utf8'            # Optional, defaults to 'utf8'
          path: './backend/data/config'                   # Optional, defaults to '.'
      - name: set access token
        uses: mingjun97/file-regex-replace@master
        with:
          regex: '<OPENAI_WEB_ACCESS_TOKEN>'
          replacement: ${{ secrets.OPENAI_WEB_ACCESS_TOKEN }}
          flags: "g"                  # Optional, defaults to "g"
          include: 'credentials.yaml'    # Optional, defaults to ".*"
          exclude: '.^'               # Optional, defaults to '.^'
          encoding: 'utf8'            # Optional, defaults to 'utf8'
          path: './backend/data/config'                   # Optional, defaults to '.'
      - name: set access token
        uses: mingjun97/file-regex-replace@master
        with:
          regex: '<OPENAI_WEB_PUID>'
          replacement: ${{ secrets.OPENAI_WEB_PUID }}
          flags: "g"                  # Optional, defaults to "g"
          include: 'credentials.yaml'    # Optional, defaults to ".*"
          exclude: '.^'               # Optional, defaults to '.^'
          encoding: 'utf8'            # Optional, defaults to 'utf8'
          path: './backend/data/config'                   # Optional, defaults to '.'
      - name: set openai api key
        uses: mingjun97/file-regex-replace@master
        with:
          regex: '<OPENAI_API_KEY>'
          replacement: ${{ secrets.OPENAI_API_KEY }}
          flags: "g"                  # Optional, defaults to "g"
          include: 'credentials.yaml'    # Optional, defaults to ".*"
          exclude: '.^'               # Optional, defaults to '.^'
          encoding: 'utf8'            # Optional, defaults to 'utf8'
          path: './backend/data/config'                   # Optional, defaults to '.'
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
